service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1


# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::module-5-upload-s3"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::module-5-upload-s3/*"


functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: module-5-upload-s3
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
